version: '3.7'
networks:
  pan:
services:
  proxy:
    container_name: proxy
    hostname: proxy
    build:
      context: ./proxy
      args:
        - SECRET=EGZk0r5buXc5YlKHpoMaluUxNkzIq1
    env_file:
      - ./.env
    networks:
      - pan
    ports:
      - 80:80
      - 443:443
    restart: always
  web:
    container_name: web
    hostname: web
    image: web:latest
    build:
      context: ./web
      args:
        - SECRET=EGZk0r5buXc5YlKHpoMaluUxNkzIq1
    env_file:
      - ./.env
    networks:
      - pan
    restart: always




